batch_size: 24
fps: 20
couch_1:
 preparation: False # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: 5
 video_path: "data/video/couch_ashley.mp4"
 audio_clips:
     #audio_0: "data/audio/eng.wav"
     audio_0: "data/audio/test.wav"
 
  

